/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import kakashiScene from '../assets/3d/Kakashi.glb'

const Kakashi = ({kakaAnimation, setKakaAnimation, ...props}) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(kakashiScene)
  const { actions } = useAnimations(animations, group)

  useEffect( ()=> {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[kakaAnimation]) {
        actions[kakaAnimation].play();
    }
  },[kakaAnimation,actions])  

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            name="0006_chr0160_damage_A"
            geometry={nodes['0006_chr0160_damage_A'].geometry}
            material={materials['Mat.3']}
            skeleton={nodes['0006_chr0160_damage_A'].skeleton}
          />
          <skinnedMesh
            name="0007_chr0160_damage_AB"
            geometry={nodes['0007_chr0160_damage_AB'].geometry}
            material={materials['Mat.10']}
            skeleton={nodes['0007_chr0160_damage_AB'].skeleton}
          />
          <skinnedMesh
            name="0009_chr0160_damage_AB_form2"
            geometry={nodes['0009_chr0160_damage_AB_form2'].geometry}
            material={materials['Mat.4']}
            skeleton={nodes['0009_chr0160_damage_AB_form2'].skeleton}
          />
          <skinnedMesh
            name="0011_chr0160_facial1"
            geometry={nodes['0011_chr0160_facial1'].geometry}
            material={materials['Mat.10']}
            skeleton={nodes['0011_chr0160_facial1'].skeleton}
          />
          <skinnedMesh
            name="0012_chr0160_form0"
            geometry={nodes['0012_chr0160_form0'].geometry}
            material={materials['Mat.8']}
            skeleton={nodes['0012_chr0160_form0'].skeleton}
          />
          <skinnedMesh
            name="0013_chr0160_form1"
            geometry={nodes['0013_chr0160_form1'].geometry}
            material={materials['Mat.2']}
            skeleton={nodes['0013_chr0160_form1'].skeleton}
          />
          <skinnedMesh
            name="0015_chr0160_damage_A"
            geometry={nodes['0015_chr0160_damage_A'].geometry}
            material={materials['Mat.3']}
            skeleton={nodes['0015_chr0160_damage_A'].skeleton}
          />
          <skinnedMesh
            name="0016_chr0160_facial1"
            geometry={nodes['0016_chr0160_facial1'].geometry}
            material={materials['Mat.9']}
            skeleton={nodes['0016_chr0160_facial1'].skeleton}
          />
          <skinnedMesh
            name="0018_chr0160_form1"
            geometry={nodes['0018_chr0160_form1'].geometry}
            material={materials['Mat.1']}
            skeleton={nodes['0018_chr0160_form1'].skeleton}
          />
          <skinnedMesh
            name="0019_chr0160_facial1"
            geometry={nodes['0019_chr0160_facial1'].geometry}
            material={materials['Mat.9']}
            skeleton={nodes['0019_chr0160_facial1'].skeleton}
          />
          <skinnedMesh
            name="0022_chr0160_form0"
            geometry={nodes['0022_chr0160_form0'].geometry}
            material={materials['Mat.5']}
            skeleton={nodes['0022_chr0160_form0'].skeleton}
          />
          <skinnedMesh
            name="0023_chr0160_form0"
            geometry={nodes['0023_chr0160_form0'].geometry}
            material={materials['Mat.4']}
            skeleton={nodes['0023_chr0160_form0'].skeleton}
          />
          <skinnedMesh
            name="0024_chr0160_form0"
            geometry={nodes['0024_chr0160_form0'].geometry}
            material={materials['Mat.3']}
            skeleton={nodes['0024_chr0160_form0'].skeleton}
          />
          <primitive object={nodes.chr0160} />
        </group>
      </group>
    </group>
  )
}

export default Kakashi
